project:
  type: website

website:
  title: "Sunny Bak"
  navbar:
    left:
      - href: index.md
        text: Home
      - about.md
format:
  html:
    theme: minty 
    css: styles.css
    toc: true
execute:
    freeze: auto



